title: Palin_drome or Elijah Martin  # You can add your name here

logo: discordPF.png # Use a relative path to logo image 

description: A list of all jams I have participated in

show_downloads: false 

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

itch: palin-drome.itch.io
